name: CI

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  test-and-build:
    name: Test and Build
    uses: imccausl/dev-scripts/.github/workflows/test-and-build.yml@main

  publish:
    name: Publish
    if: |
      github.event_name == 'push' &&
      github.ref_name == github.event.repository.default_branch
    needs: test-and-build
    uses: imccausl/dev-scripts/.github/workflows/publish.yml@main
    secrets: inherit
