name: Publish to NPM

on:
  workflow_call:

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Prepare Env
        uses: ./.github/actions/prepare-env

      - name: Restore cache
        id: restore-cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: lib
          key: lib-${{ hashFiles('**/yarn.lock', '**/package.json', '**/src/**/*') }}

      - name: Build if not cached
        if: steps.restore-cache.outputs.cache-hit != 'true'
        run: yarn build
      - name: Publish
        run: yarn publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
