name: Publish to NPM

on:
  workflow_call:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Prepare Env
        uses: ./.github/actions/prepare-env

      - name: Restore cache
        id: restore-cache
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: lib
          key: lib-${{ hashFiles('**/yarn.lock', '**/package.json', '**/src/**/*') }}

      - name: Build if not cached
        if: steps.restore-cache.outputs.cache-hit != 'true'
        run: yarn build

      - name: Publish
        run: yarn publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
